# Generated by Django 3.2.25 on 2025-02-22 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('RECEIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendedby_id', to='app.user')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivedby_id', to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=3000)),
                ('date', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('Complaint', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Replay', models.CharField(max_length=500)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
                ('POST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=100)),
                ('seen', models.CharField(max_length=100)),
                ('RECEIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='app.user')),
                ('SENDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='app.user')),
            ],
        ),
    ]
